### ISSUE TITLE
Colorama master doesn't work with The Fuck; 0.3.3 partly works; 0.3.2 works

### ISSUE THREAD

**Issue by hugovk** [tartley/colorama#77]
Windows 7, Python 2.7, Git BASH.
- [The Fuck](https://github.com/nvbn/thefuck) works properly with Colorama 0.3.2.
- The Fuck works with Colorama 0.3.3 but the text isn't coloured and it prints characters like `←[1m`.
- The Fuck doesn't work with Colorama master branch and the text isn't coloured and it prints characters like `←[1m`.

---
# Install latest dev version:

``` bash
~/github/colorama (master)
$ python setup.py develop
running develop
running egg_info
writing colorama.egg-info\PKG-INFO
writing top-level names to colorama.egg-info\top_level.txt
writing dependency_links to colorama.egg-info\dependency_links.txt
reading manifest file 'colorama.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'colorama.egg-info\SOURCES.txt'
running build_ext
Creating c:\python27\lib\site-packages\colorama.egg-link (link to .)
Adding colorama 0.3.3 to easy-install.pth file

Installed c:\users\hugovk\github\colorama
Processing dependencies for colorama==0.3.3
Finished processing dependencies for colorama==0.3.3
```

Create a new branch, try and push it, then use [The Fuck](https://github.com/nvbn/thefuck) to push it properly:

``` bash
~/github/colorama (master)
$ git checkout -b test_branch1
Switched to a new branch 'test_branch1'

~/github/colorama (test_branch1)
$ git push
fatal: The current branch test_branch1 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin test_branch1


~/github/colorama (test_branch1)
$ fuck
←[1mgit push --set-upstream origin test_branch1←[0m
fatal: remote part of refspec is not a valid name in
Unexpected end of command stream
```

Text was monochrome, command didn't work.

---
# Try the same thing with Colorama 0.3.2:

``` bash
~/github/colorama (test_branch1)
$ pip install colorama==0.3.2
Collecting colorama==0.3.2
  Using cached colorama-0.3.2.tar.gz
Installing collected packages: colorama
  Found existing installation: colorama 0.3.3
    Uninstalling colorama-0.3.3:
      Successfully uninstalled colorama-0.3.3
  Running setup.py install for colorama
Successfully installed colorama-0.3.3

~/github/colorama (test_branch1)
$ git push
fatal: The current branch test_branch1 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin test_branch1


~/github/colorama (test_branch1)
$ fuck
git push --set-upstream origin test_branch1
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/hugovk/colorama
 * [new branch]      test_branch1 -> test_branch1
Branch test_branch1 set up to track remote branch test_branch1 from origin.
```

The command worked, and those last five lines were coloured light grey.

---
# And with Colorama 0.3.3:

``` bash
~/github/colorama (test_branch1)
$ pip install colorama==0.3.3
Collecting colorama==0.3.3
  Using cached colorama-0.3.3.tar.gz
Installing collected packages: colorama
  Found existing installation: colorama 0.3.2
    Uninstalling colorama-0.3.2:
      Successfully uninstalled colorama-0.3.2
  Running setup.py install for colorama
Successfully installed colorama-0.3.3

~/github/colorama (test_branch1)
$ git checkout -b test_branch2
Switched to a new branch 'test_branch2'

~/github/colorama (test_branch2)
$ git push
fatal: The current branch test_branch2 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin test_branch2


~/github/colorama (test_branch2)
$ fuck
←[1mgit push --set-upstream origin test_branch2←[0m
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/hugovk/colorama
 * [new branch]      test_branch2 -> test_branch2
Branch test_branch2 set up to track remote branch test_branch2 from origin.
```

The command worked, but the text is monochrome and shows `←[1m` type characters.

---

Note the above was with thefuck==1.45, but similar results are had with latest thefuck==3.1.

**Comment by wiggin15** [comment]
There was a problem with git bash that was corrected not long ago. Can you please try to use the latest code in the current repository?

**Comment by hugovk** [comment]
I've updated Git Bash (my last one was installed in October 2014) and (with thefuck==1.45) it works with Colorama 0.3.2 and 0.3.3 but not master:

```bash
$ fuck
git push --set-upstream origin test_branch9
fatal: remote part of refspec is not a valid name in
```

**Comment by blueyed** [comment]
Possibly caused by https://github.com/tartley/colorama/commit/44dc8af9bc8111b70dd046a822bb26c851ba3687?
Maybe fixed by #84 ?

**Comment by wiggin15** [comment]
The commit you referenced is from December 2015 but the last comment here is from October 2015 so I don't think the two are related.

**Comment by wiggin15** [comment]
This has something to do with the use of 'eval' by thefuck. The following works with colors:

     $ thefuck git pul
     git pull [enter//ctrl+c]
     git pull

but the way that thefuck's alias works, with eval, doesn't:

    $ TF_ALIAS=fuck eval $(thefuck git pul)
    ←[1mgit pull←[0m [←[32menter←[0m/←[34mΓåæ←[0m/←[34mΓåô←[0m/←[31mctrl+c←[0m]
    fatal: Not a git repository (or any of the parent directories): .git

Maybe 'eval' changes some property of stdout/stderr, and the changes made in colorama for 'strip'/convert may not work with it. I'm still not sure about this, though, because running 'eval $(echo python script.py)', where 'script.py' prints colors, does work...

**Comment by felixonmars** [comment]
I can confirm that #84 fixes this for me on both bash and fish, under Linux.

**Comment by wiggin15** [comment]
@felixonmars the original report on this ticket is for an issue with Git Bash on Windows. Applying #84 did not resolve the issue on my system. I wasn't aware that there's an issue on bash/fish on Linux. Can you please describe your original problem on Linux, fixed by #84? Thanks

**Comment by felixonmars** [comment]
That came from a note on the colorama package of Arch. Just double-checked that this is unrelated. Really sorry for the confusion.

**Comment by AndreLouisCaron** [comment]
Since this is specific to Windows and @wiggin15 mentionned the fact that it doesn't work when using `eval $(...)`, I'm curious to see whether this issues is related to issue #95?  The fix for that was merged in PR #97 and master should contain it.

**Comment by wiggin15** [comment]
@AndreLouisCaron looks like you're right :) Thank you very much!!
@hugovk can you please use the latest code and verify that it works for you too?

**Comment by hugovk** [comment]
Windows 7, Python 2.7, Git BASH.

 * thefuck==3.9
 * colorama==0.3.7

Now get:

```bash
  File "c:\python27\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 0: ordinal not in range(128)
```

Full trace:

```bash
$ pip install -U thefuck
Collecting thefuck
  Downloading thefuck-3.9-py2.py3-none-any.whl (75kB)
Collecting psutil (from thefuck)
  Downloading psutil-4.2.0-cp27-cp27m-win_amd64.whl (167kB)
Requirement already up-to-date: colorama in c:\python27\lib\site-packages (from thefuck)
Requirement already up-to-date: pathlib; python_version < "3.4" in c:\python27\lib\site-packages (from thefuck)
Requirement already up-to-date: six in c:\python27\lib\site-packages (from thefuck)
Collecting decorator (from thefuck)
  Downloading decorator-4.0.9-py2.py3-none-any.whl
Collecting win-unicode-console; sys_platform == "win32" (from thefuck)
  Downloading win_unicode_console-0.4.zip
Installing collected packages: psutil, decorator, win-unicode-console, thefuck
  Found existing installation: psutil 3.2.2
    Uninstalling psutil-3.2.2:
      Successfully uninstalled psutil-3.2.2
  Found existing installation: decorator 4.0.4
    Uninstalling decorator-4.0.4:
      Successfully uninstalled decorator-4.0.4
  Running setup.py install for win-unicode-console: started
    Running setup.py install for win-unicode-console: finished with status 'done'
  Found existing installation: thefuck 1.49.1
    Uninstalling thefuck-1.49.1:
      Successfully uninstalled thefuck-1.49.1
Successfully installed decorator-4.0.9 psutil-4.2.0 thefuck-3.9 win-unicode-console-0.4

$ pip freeze | grep "fuck"
thefuck==3.9

$ pip freeze | grep "colorama"
colorama==0.3.7

$ git checkout -b test_branch
Switched to a new branch 'test_branch'

$ git push
fatal: The current branch test_branch has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin test_branch


$ fuck
git push --set-upstream origin test_branch [enter/Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\thefuck.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\thefuck\main.py", line 80, in main
    fix_command()
  File "c:\python27\lib\site-packages\thefuck\main.py", line 32, in fix_command
    selected_command = select_command(corrected_commands)
  File "c:\python27\lib\site-packages\thefuck\ui.py", line 78, in select_command
    logs.confirm_text(selector.value)
  File "c:\python27\lib\site-packages\thefuck\logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
  File "c:\python27\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "c:\python27\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "c:\python27\lib\site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "c:\python27\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 0: ordinal not in range(128)

$
```

**Comment by wiggin15** [comment]
@hugovk looks like you are now encountering the problem reported in issue #36.
You added unicode characters to your output (↑) so we are seeing a different problem now (by the way, when I tried, I couldn't print this character in Windows cmd even without colorama)

**Comment by hugovk** [comment]
Closing, I'm not using Windows much now and I've not seen this on macOS.
